[disk]
partition_table_type = "gpt"

  [[disk.partitions]]
  name = "BIOS boot"
  fs = "fat32"
  start = "1MiB"
  end = "2MiB"
  flags = [
    "bios_grub"
  ]

  [[disk.partitions]]
  name = "EFI system"
  fs = "fat32"
  start = "2MiB"
  end = "258MiB"

  [[disk.partitions]]
  name = "Linux"
  fs = "btrfs"
  start = "258MiB"
  end = "-4001MiB"
  subvolumes = [
    "@",
    "@home"
  ]

  [[disk.partitions]]
  name = "Linux swap"
  fs = "linux-swap"
  start = "-4001MiB"
  end = "-1MiB"
